feat(icons): add the paint bucket icons
coveo/plasma pull request #2453
Opened 2022-02-10 22:17 UTC by sallainCoveo

### Proposed Changes
Main story: https://coveord.atlassian.net/browse/SPAAS-1112
subtask: https://coveord.atlassian.net/browse/SPAAS-1113

Only to add the paint bucket icons in Plasma, it will be useful for the builder!

### Potential Breaking Changes
No breaking changes

### Acceptance Criteria

-   [ ] The proposed changes are covered by unit tests
-   [ ] The potential breaking changes are clearly identified
-   [ ] [README.md](https://github.com/coveo/plasma/blob/master/README.md) is adjusted to reflect the proposed changes (if relevant)

2022-02-10 22:27 UTC, mikedidomizio approved these changes

2022-02-11 12:24 UTC, aiheon approved these changes

2022-02-11 15:52 UTC, kdang-coveo commented
Hey Sylvie, the paintbuckets do not respect the mod-classes being applied e.g:
<img width="1346" alt="CleanShot 2022-02-11 at 10 51 29@2x" src="https://user-images.githubusercontent.com/66333175/153623671-0e74dea2-c5c5-4404-aef5-02adec9cb40b.png">

<img width="1348" alt="CleanShot 2022-02-11 at 10 51 41@2x" src="https://user-images.githubusercontent.com/66333175/153623718-e225fef7-ed06-4895-b8b2-0090357c2b78.png">

I think they should respect the mod-classes, we might need to ask UX to revise these svgs unless its okay for just the same stroke colour

2022-02-11 16:01 UTC, sallainCoveo commented
> Hey Sylvie, the paintbuckets do not respect the mod-classes being applied e.g: <img alt="CleanShot 2022-02-11 at 10 51 29@2x" width="1346" src="https://user-images.githubusercontent.com/66333175/153623671-0e74dea2-c5c5-4404-aef5-02adec9cb40b.png">
> 
> <img alt="CleanShot 2022-02-11 at 10 51 41@2x" width="1348" src="https://user-images.githubusercontent.com/66333175/153623718-e225fef7-ed06-4895-b8b2-0090357c2b78.png">
> 
> I think they should respect the mod-classes, we might need to ask UX to revise these svgs unless its okay for just the same stroke colour

Oh no! I don't think it will have an impact on the current project, but still I think it's worth looking into it before we merge those ones. @johnnyCoveo what do you think about it?

2022-02-11 17:07 UTC, gdostie requested changes
We cannot leave strokes directly on paths, otherwise we won't be able to apply colors on the icons with css

2022-02-11 17:07 UTC, gdostie commented on packages/style/resources/icons/svg/paint-bucket-16px.svg
> +</svg>
Move the `stoke` attributes to the root `svg` tag plz

2022-02-14 18:00 UTC, gdostie requested changes
No stroke attribute on the paths directly please 😄

2022-02-14 18:00 UTC, gdostie commented on packages/style/resources/icons/svg/paint-bucket-16px.svg
> +<path d="M15.5 14.1449C15.5 14.9084 14.9082 15.5 14.1481 15.5C13.388 15.5 12.7963 14.9084 12.7963 14.1449C12.7963 13.9919 12.8756 13.6876 13.0495 13.2556C13.2145 12.8455 13.4378 12.3838 13.6658 11.94
```suggestion
<path d="M15.5 14.1449C15.5 14.9084 14.9082 15.5 14.1481 15.5C13.388 15.5 12.7963 14.9084 12.7963 14.1449C12.7963 13.9919 12.8756 13.6876 13.0495 13.2556C13.2145 12.8455 13.4378 12.3838 13.6658 11.9453C13.8332 11.6235 14.0008 11.3183 14.146 11.061C14.292 11.322 14.4611 11.632 14.6299 11.9583C14.8581 12.3995 15.0817 12.8629 15.247 13.2719C15.4219 13.7045 15.5 14.0026 15.5 14.1449Z" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
```

2022-02-14 18:00 UTC, gdostie commented on packages/style/resources/icons/svg/paint-bucket-24px.svg
> +<path d="M21.5 19.6811C21.5 20.7044 20.7045 21.5 19.6852 21.5C18.6658 21.5 17.8704 20.7044 17.8704 19.6811C17.8704 19.4632 17.9786 19.0627 18.1959 18.5229C18.4044 18.0049 18.6855 17.4238 18.9714 16.8
```suggestion
<path d="M21.5 19.6811C21.5 20.7044 20.7045 21.5 19.6852 21.5C18.6658 21.5 17.8704 20.7044 17.8704 19.6811C17.8704 19.4632 17.9786 19.0627 18.1959 18.5229C18.4044 18.0049 18.6855 17.4238 18.9714 16.874C19.2249 16.3864 19.4789 15.9296 19.683 15.5723C19.8878 15.934 20.1434 16.3973 20.3985 16.8905C20.6845 17.4435 20.966 18.0266 21.1747 18.5431C21.3929 19.083 21.5 19.4762 21.5 19.6811Z" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
```

2022-02-14 18:00 UTC, gdostie commented on packages/style/resources/icons/svg/paint-bucket-32px.svg
> +<path d="M29.5 26.7536C29.5 28.2963 28.2971 29.5 26.7593 29.5C25.2214 29.5 24.0186 28.2963 24.0186 26.7536C24.0186 26.4058 24.1847 25.8128 24.4888 25.0574C24.784 24.3238 25.181 23.5038 25.5825 22.731
```suggestion
<path d="M29.5 26.7536C29.5 28.2963 28.2971 29.5 26.7593 29.5C25.2214 29.5 24.0186 28.2963 24.0186 26.7536C24.0186 26.4058 24.1847 25.8128 24.4888 25.0574C24.784 24.3238 25.181 23.5038 25.5825 22.7314C25.9833 21.9605 26.3847 21.2448 26.6862 20.7213C26.7105 20.6791 26.7341 20.6382 26.757 20.5987C26.781 20.6405 26.8058 20.6839 26.8313 20.7286C27.133 21.2574 27.5345 21.9795 27.9355 22.7548C28.3373 23.5316 28.7346 24.3542 29.0301 25.0854C29.3351 25.8401 29.5 26.4234 29.5 26.7536Z" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
```

2022-02-15 17:43 UTC, kdang-coveo approved these changes

2022-02-15 18:57 UTC, gdostie approved these changes

2022-02-15 18:57 UTC, gdostie commented on packages/style/resources/icons/svg/paint-bucket-16px.svg
> +<svg viewBox="0 0 16 16" fill="none" stroke="black" xmlns="http://www.w3.org/2000/svg">
All of our other icons have grey-100 has a default color

```suggestion
<svg viewBox="0 0 16 16" fill="none" stroke="#282829" xmlns="http://www.w3.org/2000/svg">
```

2022-02-15 18:57 UTC, gdostie commented on packages/style/resources/icons/svg/paint-bucket-24px.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="black">
```suggestion
<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#282829">
```

2022-02-15 18:57 UTC, gdostie commented on packages/style/resources/icons/svg/paint-bucket-32px.svg
> +<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="black">
```suggestion
<svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#282829">
```

2022-02-15 19:59 UTC, merged